### ISSUE TITLE
Документирование парковки домена

### ISSUE THREAD

**Issue by DmitryUspensky** [u-transnet/transnet.space#1]
Необходимо задокументировать процесс парковки домена на дроплете DigitalOcean

**Comment by DmitryUspensky** [comment]
[Блок](https://wallet.bitshares.eu/block/21988662) принятия в работу. 65.00000 UTDEV.SKILL до 21.11.2017

**Comment by DmitryUspensky** [comment]
[Результат](https://github.com/u-transnet/transnet.space/wiki/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-%D0%BF%D0%B0%D1%80%D0%BA%D0%BE%D0%B2%D0%BA%D0%B5-%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD%D0%B0-%D0%BD%D0%B0-%D0%B4%D1%80%D0%BE%D0%BF%D0%BB%D0%B5%D1%82%D0%B5-DigitalOcean)

**Comment by DmitryUspensky** [comment]
@kkrupovich проверяй

**Comment by cptn-solo** [comment]
Обалденно :) Димыч, ты мой герой. Садись, пять.

**Comment by cptn-solo** [comment]
BLOCK #21993670 uspenskydmitry1970 65UTDEV, возмещение в полном объеме, спасибо!
