### ISSUE TITLE
Документирование выпуска ssl сертификата

### ISSUE THREAD

**Issue by DmitryUspensky** [u-transnet/transnet.space#2]
Необходимо задокументировать процесс получения ssl сертификата

**Comment by DmitryUspensky** [comment]
[Блок](https://wallet.bitshares.eu/block/21993629) принятия в работу. 65.00000 UTDEV.SKILL до 21.11.2017

**Comment by DmitryUspensky** [comment]
[Результат](https://github.com/u-transnet/transnet.space/wiki/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8E-%D0%B8-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B5-%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-ssl-%D1%81%D0%B5%D1%80%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%B0)

**Comment by DmitryUspensky** [comment]
@kkrupovich, готово

**Comment by cptn-solo** [comment]
Все ок, спасибо, закрываю.

**Comment by cptn-solo** [comment]
BLOCK #21993822 uspenskydmitry1970 65UTDEV, возмещение в полном объеме, спасибо!
