### ISSUE TITLE
Выпуск ssl сертификата и конфигурирование Nginx на 443 порту

### ISSUE THREAD

**Issue by DmitryUspensky** [u-transnet/transnet.space#3]
Разобраться и получить мультидоменный ssl сертификат и положить его под домены transnet.space и transnet.tech

**Comment by DmitryUspensky** [comment]
[Блок](https://wallet.bitshares.eu/block/21993775) принятия в работу, 125 UTDEV.SKILL, 21.11.2017

**Comment by DmitryUspensky** [comment]
@kkrupovich проверяй 
* https://transnet.space 
* https://transnet.tech

**Comment by cptn-solo** [comment]
BLOCK #21994370 uspenskydmitry1970 125UTDEV, полное возмещение, спасибо!
