### ISSUE TITLE
Сконфигурировать порты

### ISSUE THREAD

**Issue by DmitryUspensky** [u-transnet/transnet.space#4]
Настроить порты:
* 80 - заглушка 404 (глитч)
* 443 - заглушка ssl (тот же глитч)
* 10443 - морда ssl (загрузка самого кошелька)
* faucet сделать ssl (https:// - js кошелька должен ломиться в фасет так)

**Comment by DmitryUspensky** [comment]
[Блок](https://wallet.bitshares.eu/block/22015949) принятия в работу. 85 UTDEV.SKILL, срок выполнения до 22.11.2017

**Comment by DmitryUspensky** [comment]
@kkrupovich проверяй 
* 80 - заглушка 404 (глитч) http://transnet.space/
* 443 - заглушка ssl (тот же глитч) https://transnet.space/
* 10443 - морда ssl (загрузка самого кошелька) https://transnet.space:10443
* faucet сделать ssl (https:// - js кошелька должен ломиться в фасет так) https://transnet.space:10443/api

**Comment by cptn-solo** [comment]
BLOCK #22019540 uspenskydmitry1970 85UTDEV спасибо
