### ISSUE TITLE
Поправить зависимости utransnet-ui

### ISSUE THREAD

**Issue by ghost** [u-transnet/transnet.space#5]
Нужно поправить зависимости в [репозитории](https://github.com/u-transnet/utransnet-ui/tree/utt_nodes), чтобы зависимость bitsharesjs -> [bitsharesjs-ws](https://github.com/bitshares/bitsharesjs-ws) стала bitsharesjs -> [bitsharesjs-ws#UTT_chain](https://github.com/u-transnet/bitsharesjs-ws/tree/UTT_chain). При этом GUI должен остаться рабочим.

**Comment by kkrupovich** [comment]
@mparkhomenko дружище, а можно немного подробнее все же

**Comment by ghost** [comment]
@EvgeniyPolyakov пиши мне в телеграм по всем вопросам по данной задаче

**Comment by ghost** [comment]
BLOCK #23652023
map-13
50UTDEV.SKILL
18.01.2018
помогал @EvgeniyPolyakov с попытками собрать это дело и настройками nginx

**Comment by ghost** [comment]
@EvgeniyPolyakov не забудь заскиловаться

**Comment by EvgeniyPolyakov** [comment]
БЛОК #23652218

От | eugene-polyakov
Кому | utd-web
Количество | 120.00000 UTDEV.SKILL

Скилл за 2 рабочих дня. Интерфейс поднялся локально, по прогнозам еще день для деплоя и настройки

**Comment by EvgeniyPolyakov** [comment]
На текущий день выявлена проблема, и есть временное решение.

**Проблема:**

форки транснета с пакетов bitsharesjs и bitsharesjs-ws ( bitsharesjs-ws я является зависимостью bitsharesjs), где необходимо установить настройки для utransnet не компилируются и соответственно не позволяют собирать общий билд. Причем единственная разница только в паре строчек с настройками - в остальном они идентичны + способ установки (зарегистрированный пакет или форк)

Встречал частое упоминание этой проблемы, некоторые указывали что в зависимости от версии node их пакет билдится по-разному.

**Что пробовал:**

- Переносить  bitsharesjs-ws в общий список зависимостей
- Пакет git-install (для коректной инсталляции форков)
- Пляски с бубном

положительного результата не было

**Временное рабочее решение:**

В сборку ставятся официальные пакеты, настройки меняются в них перед билдом. Готовый дистрибутив передается в docker. Минус пока довольно незначителен - перед каждой сборкой надо менять пару строчек. Из плюсов - можно исключить билд при сборке докера.

**Рабочая гипотеза для проверки:**

Возможно эти пакеты не билдятся из-за того что не все их зависимости подтягиваются как таковые - ведь форки загружаются иначе ( "git+http...."), а пакет "git-install" не помог. Как вариант попробую перенести из package.json этих форк-пакетов недостающие зависимости в список общих зависимостей.

На данный момент у нас есть рабочее решение в виде готового, рабочего и  кастомизированного веб-интерфейса с нужными настройками для  u-transnet. К проверке гипотезы и полное решение проблемы зависимости планирую в ближайшее окно для рефакторинга

![2018-01-19 0 25 19 2](https://user-images.githubusercontent.com/13783084/35220306-aac38888-ff97-11e7-88bf-e9d52efa79cd.jpg)

закрываем итерацию и уходим сюда https://github.com/u-transnet/transnet.space/issues/7

**Comment by EvgeniyPolyakov** [comment]
БЛОК #23757739

От | eugene-polyakov
Кому | utd-web
Количество | 120.00000 UTDEV.SKILL

добавочный скилл на 2 дня в предыдущим

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov 

BLOCK #23764465

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 240.00000 UTDEV

@mparkhomenko 

BLOCK #23764503

TRANSFER |  
-- | --
From | utd-core
To | map-13
Quantity | 50.00000 UTDEV

Спасибо, парни.
